const seedData = {
  user: {
    name: "Tester",
    email: "test@example.com",
    password: "Test@123",
  },
  projects: [
    // Project 1: Website Redesign
    {
      title: "E-commerce Website Redesign",
      description: "Complete overhaul of the company's online store for enhanced UX/UI and performance.",
      status: "active",
      tasks: [
        { title: "Conduct stakeholder interviews", description: "Gather requirements from marketing, sales, and IT.", dueDate: "29-09-2025", status: "done" },
        { title: "Analyze competitor websites", description: "Identify strengths and weaknesses of key competitors.", dueDate: "30-09-2025", status: "done" },
        { title: "Create user personas and journey maps", description: "Define target audience and their interaction flows.", dueDate: "01-10-2025", status: "done" },
        { title: "Develop detailed wireframes", description: "Design the skeletal framework of all major pages using Figma.", dueDate: "03-10-2025", status: "done" },
        { title: "Design high-fidelity UI mockups", description: "Create the final visual design based on brand guidelines.", dueDate: "06-10-2025", status: "done" },
        { title: "Set up frontend development environment", description: "Configure repository, frameworks (React), and build tools.", dueDate: "07-10-2025", status: "in-progress" },
        { title: "Implement homepage and navigation", description: "Code the main landing page and global navigation components.", dueDate: "10-10-2025", status: "in-progress" },
        { title: "Develop product listing and detail pages", description: "Build the templates for displaying product collections and individual items.", dueDate: "14-10-2025", status: "in-progress" },
        { title: "Build shopping cart and checkout flow", description: "Implement all steps from adding to cart to payment confirmation.", dueDate: "17-10-2025", status: "in-progress" },
        { title: "Integrate payment gateway (Stripe)", description: "Connect the checkout system with the payment processor API.", dueDate: "20-10-2025", status: "in-progress" },
        { title: "Develop user account and order history pages", description: "Allow users to manage their profile and view past orders.", dueDate: "22-10-2025", status: "todo" },
        { title: "Conduct cross-browser and device testing", description: "Ensure compatibility across Chrome, Firefox, Safari, and mobile devices.", dueDate: "24-10-2025", status: "todo" },
        { title: "Perform user acceptance testing (UAT)", description: "Have internal stakeholders test the site before launch.", dueDate: "27-10-2025", status: "todo" },
        { title: "Deploy to production server", description: "Go-live with the new website.", dueDate: "30-10-2025", status: "todo" },
        { title: "Monitor post-launch performance", description: "Track analytics and user feedback for a week after launch.", dueDate: "07-11-2025", status: "todo" },
      ],
    },
    // Project 2: Mobile App Development
    {
      title: "Mobile App Development (Project Connect)",
      description: "Build a new social networking mobile app for iOS and Android.",
      status: "active",
      tasks: [
        { title: "Finalize app features and MVP scope", description: "Define the core functionalities for the first release.", dueDate: "01-10-2025", status: "done" },
        { title: "Choose technology stack", description: "Decide on programming languages and frameworks (e.g., React Native).", dueDate: "02-10-2025", status: "done" },
        { title: "Design database schema", description: "Plan the structure of the user, post, and connections tables.", dueDate: "04-10-2025", status: "done" },
        { title: "Create UI/UX designs for all screens", description: "Design the complete user interface in Figma.", dueDate: "08-10-2025", status: "done" },
        { title: "Set up backend server and APIs", description: "Develop the server-side logic and endpoints.", dueDate: "11-10-2025", status: "in-progress" },
        { title: "Implement user authentication (signup/login)", description: "Code the user registration and login functionality.", dueDate: "15-10-2025", status: "in-progress" },
        { title: "Develop user profile screen", description: "Build the screen where users can view and edit their profiles.", dueDate: "18-10-2025", status: "in-progress" },
        { title: "Code the main content feed", description: "Implement the scrolling feed to display posts from connections.", dueDate: "22-10-2025", status: "in-progress" },
        { title: "Implement real-time chat feature", description: "Integrate a messaging system using WebSockets.", dueDate: "27-10-2025", status: "todo" },
        { title: "Set up push notifications", description: "Configure services for sending notifications to users.", dueDate: "30-10-2025", status: "todo" },
        { title: "Internal Alpha testing", description: "Distribute the app to the internal team for initial feedback.", dueDate: "04-11-2025", status: "todo" },
        { title: "Recruit external beta testers", description: "Invite a select group of users for a closed beta test.", dueDate: "07-11-2025", status: "todo" },
        { title: "Prepare for App Store submission", description: "Create all necessary assets and metadata for Apple.", dueDate: "12-11-2025", status: "todo" },
        { title: "Prepare for Google Play Store submission", description: "Create all necessary assets and metadata for Google.", dueDate: "12-11-2025", status: "todo" },
        { title: "Launch app on both stores", description: "Officially release the app to the public.", dueDate: "19-11-2025", status: "todo" },
      ],
    },
    // Project 3: Marketing Campaign
    {
      title: "Q4 Holiday Marketing Campaign",
      description: "Plan and launch the fall marketing campaign to boost holiday sales.",
      status: "active",
      tasks: [
        { title: "Define campaign goals and KPIs", description: "Set specific targets for sales, traffic, and engagement.", dueDate: "29-09-2025", status: "done" },
        { title: "Identify target audience segments", description: "Define customer profiles for personalized marketing.", dueDate: "01-10-2025", status: "done" },
        { title: "Develop campaign creative concept", description: "Brainstorm the main theme and messaging for the campaign.", dueDate: "03-10-2025", status: "done" },
        { title: "Create ad creatives for social media", description: "Design visuals for Facebook, Instagram, and TikTok ads.", dueDate: "08-10-2025", status: "in-progress" },
        { title: "Write ad copy and headlines", description: "Come up with catchy headlines and calls-to-action.", dueDate: "10-10-2025", status: "in-progress" },
        { title: "Produce short-form video ads", description: "Create engaging video content for social media platforms.", dueDate: "15-10-2025", status: "in-progress" },
        { title: "Set up email automation sequences", description: "Use Mailchimp to automate follow-up and promotional emails.", dueDate: "17-10-2025", status: "in-progress" },
        { title: "Schedule organic social media posts", description: "Plan and prepare content for the entire campaign period.", dueDate: "20-10-2025", status: "todo" },
        { title: "Configure Google Ads and PPC campaigns", description: "Set up search, display, and shopping ads.", dueDate: "22-10-2025", status: "todo" },
        { title: "Collaborate with influencers", description: "Partner with influencers for sponsored posts.", dueDate: "24-10-2025", status: "todo" },
        { title: "Finalize marketing budget allocation", description: "Distribute the budget across all channels.", dueDate: "27-10-2025", status: "todo" },
        { title: "Launch all campaign activities", description: "Go live with all planned marketing efforts.", dueDate: "01-11-2025", status: "todo" },
        { title: "Monitor daily campaign performance", description: "Track KPIs and adjust strategies as needed.", dueDate: "15-11-2025", status: "todo" },
        { title: "Prepare weekly performance reports", description: "Summarize results for stakeholders.", dueDate: "22-11-2025", status: "todo" },
        { title: "Conduct post-campaign analysis", description: "Evaluate overall success and gather learnings for the future.", dueDate: "15-12-2025", status: "todo" },
      ],
    },
    // Project 4: New Product Launch
    {
        title: "Launch 'Aura' Smart Home Hub",
        description: "Coordinate the launch of our next-generation smart home device.",
        status: "active",
        tasks: [
            { title: "Finalize hardware specifications", description: "Lock in the final components and technical specs.", dueDate: "30-09-2025", status: "done" },
            { title: "Complete industrial design and CMF", description: "Finalize Color, Material, and Finish for the product.", dueDate: "03-10-2025", status: "done" },
            { title: "Design product packaging", description: "Create retail packaging that is attractive and informative.", dueDate: "07-10-2025", status: "done" },
            { title: "Set up manufacturing and supply chain", description: "Finalize contracts with suppliers and manufacturers.", dueDate: "10-10-2025", status: "in-progress" },
            { title: "Develop and test firmware", description: "Code the embedded software for the device.", dueDate: "15-10-2025", status: "in-progress" },
            { title: "Create marketing and press materials", description: "Prepare press releases, product photos, and videos.", dueDate: "17-10-2025", status: "in-progress" },
            { title: "Build the product landing page", description: "Create a dedicated page on our website for 'Aura'.", dueDate: "20-10-2025", status: "in-progress" },
            { title: "Plan PR and media outreach strategy", description: "Identify key journalists and publications to target.", dueDate: "22-10-2025", status: "todo" },
            { title: "Onboard retail partners", description: "Secure placement in key online and physical retail stores.", dueDate: "25-10-2025", status: "todo" },
            { title: "Plan the virtual launch event", description: "Organize an online event to announce the product.", dueDate: "28-10-2025", status: "todo" },
            { title: "Coordinate logistics and shipping", description: "Ensure inventory is in place for launch day.", dueDate: "01-11-2025", status: "todo" },
            { title: "Train customer support team", description: "Educate the support staff on the new product.", dueDate: "04-11-2025", status: "todo" },
            { title: "Execute launch day marketing blast", description: "Send out launch emails and social media announcements.", dueDate: "10-11-2025", status: "todo" },
            { title: "Monitor early customer feedback", description: "Track reviews and social media mentions.", dueDate: "17-11-2025", status: "todo" },
            { title: "Release first firmware update", description: "Address any initial bugs or feature requests.", dueDate: "01-12-2025", status: "todo" },
        ]
    },
    // ... add 8 more projects with 15 tasks each
    // Project 5: HR Portal Implementation
    {
        title: "HR Portal Implementation",
        description: "Deploy a new self-service HR portal for all employees.",
        status: "active",
        tasks: [
            { title: "Gather requirements from HR department", description: "Understand needs for payroll, leave, and benefits management.", dueDate: "01-10-2025", status: "done" },
            { title: "Evaluate and select HR software vendor", description: "Compare options like Workday, BambooHR, etc.", dueDate: "05-10-2025", status: "done" },
            { title: "Finalize contract and SOW with vendor", description: "Sign agreements and define the scope of work.", dueDate: "10-10-2025", status: "done" },
            { title: "Plan data migration from old system", description: "Create a strategy for moving employee data.", dueDate: "15-10-2025", status: "in-progress" },
            { title: "Configure user roles and permissions", description: "Set up access levels for employees, managers, and HR admins.", dueDate: "18-10-2025", status: "in-progress" },
            { title: "Customize leave and attendance policies", description: "Input company-specific rules into the new system.", dueDate: "21-10-2025", status: "in-progress" },
            { title: "Integrate with payroll system", description: "Ensure seamless data flow for salary processing.", dueDate: "25-10-2025", status: "todo" },
            { title: "Set up performance management module", description: "Configure goal setting and review templates.", dueDate: "29-10-2025", status: "todo" },
            { title: "Import all employee data", description: "Execute the data migration plan.", dueDate: "03-11-2025", status: "todo" },
            { title: "Conduct user acceptance testing with HR team", description: "Have the HR department validate all functionalities.", dueDate: "07-11-2025", status: "todo" },
            { title: "Develop employee training materials", description: "Create user guides and video tutorials.", dueDate: "11-11-2025", status: "todo" },
            { title: "Schedule and conduct employee training sessions", description: "Train all employees on how to use the new portal.", dueDate: "15-11-2025", status: "todo" },
            { title: "Go-live with the new portal", description: "Launch the HR portal for all employees.", dueDate: "20-11-2025", status: "todo" },
            { title: "Provide post-launch support", description: "Address any issues or questions from employees.", dueDate: "27-11-2025", status: "todo" },
            { title: "Decommission the old HR system", description: "Archive data and shut down the legacy system.", dueDate: "05-12-2025", status: "todo" },
        ]
    },
    // Project 6: Cloud Infrastructure Migration
    {
        title: "Cloud Infrastructure Migration to AWS",
        description: "Migrate all on-premise servers and applications to Amazon Web Services.",
        status: "active",
        tasks: [
            { title: "Inventory all on-premise applications and servers", description: "Document all current infrastructure components.", dueDate: "02-10-2025", status: "done" },
            { title: "Design the target AWS architecture", description: "Plan the VPC, subnets, EC2 instances, and RDS setup.", dueDate: "06-10-2025", status: "done" },
            { title: "Create a detailed migration plan and timeline", description: "Outline the step-by-step process for migration.", dueDate: "09-10-2025", status: "done" },
            { title: "Set up AWS account and IAM roles", description: "Configure security and access controls in AWS.", dueDate: "13-10-2025", status: "in-progress" },
            { title: "Provision networking infrastructure (VPC, Subnets)", description: "Build the foundational network in AWS.", dueDate: "16-10-2025", status: "in-progress" },
            { title: "Migrate the first non-critical application", description: "Conduct a pilot migration to test the process.", dueDate: "20-10-2025", status: "in-progress" },
            { title: "Migrate databases to Amazon RDS", description: "Move SQL databases to the managed service.", dueDate: "24-10-2025", status: "todo" },
            { title: "Migrate web servers to EC2 instances", description: "Use lift-and-shift or re-platforming methods.", dueDate: "28-10-2025", status: "todo" },
            { title: "Configure load balancers and auto-scaling", description: "Ensure high availability and performance.", dueDate: "01-11-2025", status: "todo" },
            { title: "Set up CloudWatch monitoring and alarms", description: "Implement observability for the new infrastructure.", dueDate: "05-11-2025", status: "todo" },
            { title: "Perform security audit of the new environment", description: "Check for vulnerabilities and misconfigurations.", dueDate: "09-11-2025", status: "todo" },
            { title: "Conduct performance and load testing", description: "Ensure the new environment can handle production traffic.", dueDate: "13-11-2025", status: "todo" },
            { title: "Final DNS cutover to AWS", description: "Point all production traffic to the new infrastructure.", dueDate: "18-11-2025", status: "todo" },
            { title: "Monitor system stability post-migration", description: "Closely watch performance for 72 hours.", dueDate: "21-11-2025", status: "todo" },
            { title: "Decommission on-premise hardware", description: "Power down and dispose of old servers.", dueDate: "02-12-2025", status: "todo" },
        ]
    },
    // Project 7: Office Relocation
    {
        title: "Headquarters Office Relocation",
        description: "Plan and execute the move to the new downtown office location.",
        status: "active",
        tasks: [
            { title: "Finalize lease agreement for the new office", description: "Complete all legal paperwork and negotiations.", dueDate: "30-09-2025", status: "done" },
            { title: "Hire an office design and build firm", description: "Select a contractor for the interior fit-out.", dueDate: "04-10-2025", status: "done" },
            { title: "Approve final office layout and design", description: "Sign off on the floor plan, furniture, and aesthetics.", dueDate: "10-10-2025", status: "done" },
            { title: "Plan IT infrastructure for the new office", description: "Design networking, server room, and cabling.", dueDate: "15-10-2025", status: "in-progress" },
            { title: "Select and order new office furniture", description: "Choose desks, chairs, and common area furniture.", dueDate: "18-10-2025", status: "in-progress" },
            { title: "Coordinate with building management", description: "Arrange for access for contractors and movers.", dueDate: "21-10-2025", status: "in-progress" },
            { title: "Hire a professional moving company", description: "Get quotes and book a mover for the relocation date.", dueDate: "24-10-2025", status: "todo" },
            { title: "Develop an employee communication plan", description: "Keep staff informed about the move timeline.", dueDate: "27-10-2025", status: "todo" },
            { title: "Set up internet and phone systems", description: "Ensure connectivity is ready before move-in.", dueDate: "31-10-2025", status: "todo" },
            { title: "Coordinate the physical move of equipment", description: "Manage the packing and transport of computers and files.", dueDate: "07-11-2025", status: "todo" },
            { title: "Set up workstations at the new location", description: "Assemble desks and connect IT equipment.", dueDate: "11-11-2025", status: "todo" },
            { title: "Conduct a final walkthrough of the old office", description: "Ensure the space is left in good condition.", dueDate: "14-11-2025", status: "todo" },
            { title: "Organize a 'Welcome to the new office' event", description: "Celebrate the move with the team.", dueDate: "17-11-2025", status: "todo" },
            { title: "Update company address with all vendors and clients", description: "Communicate the new address to all stakeholders.", dueDate: "20-11-2025", status: "todo" },
            { title: "Terminate lease for the old office", description: "Complete the final handover to the old landlord.", dueDate: "30-11-2025", status: "todo" },
        ]
    },
    // Project 8: Annual Company Summit
    {
        title: "Annual Company Summit 2025",
        description: "Organize the annual all-hands company summit for 500 employees.",
        status: "active",
        tasks: [
            { title: "Set event goals, theme, and budget", description: "Define the purpose and financial constraints of the summit.", dueDate: "01-10-2025", status: "done" },
            { title: "Select and book the event venue", description: "Finalize the contract with a hotel or conference center.", dueDate: "06-10-2025", status: "done" },
            { title: "Develop the summit agenda and schedule", description: "Plan the sequence of keynotes, workshops, and activities.", dueDate: "10-10-2025", status: "done" },
            { title: "Book keynote speakers and workshop facilitators", description: "Secure external and internal speakers.", dueDate: "15-10-2025", status: "in-progress" },
            { title: "Arrange travel and accommodation for attendees", description: "Book flights and hotel rooms for out-of-town employees.", dueDate: "20-10-2025", status: "in-progress" },
            { title: "Plan catering and menu selections", description: "Coordinate meals, snacks, and drinks with the venue.", dueDate: "23-10-2025", status: "in-progress" },
            { title: "Design event branding and materials", description: "Create logos, banners, presentations, and swag.", dueDate: "27-10-2025", status: "todo" },
            { title: "Launch internal registration website", description: "Allow employees to register and select sessions.", dueDate: "30-10-2025", status: "todo" },
            { title: "Coordinate with AV and production team", description: "Plan for sound, lighting, and video recording.", dueDate: "04-11-2025", status: "todo" },
            { title: "Plan team-building activities", description: "Organize an evening social or activity.", dueDate: "07-11-2025", status: "todo" },
            { title: "Send out pre-event communication to attendees", description: "Share agenda, logistics, and what to expect.", dueDate: "12-11-2025", status: "todo" },
            { title: "Finalize all vendor contracts and payments", description: "Ensure all providers are paid and confirmed.", dueDate: "17-11-2025", status: "todo" },
            { title: "On-site event execution and management", description: "Manage the summit in real-time.", dueDate: "25-11-2025", status: "todo" },
            { title: "Collect post-event feedback from attendees", description: "Send out a survey to gather feedback.", dueDate: "28-11-2025", status: "todo" },
            { title: "Conduct post-event debrief and financial reconciliation", description: "Review success and finalize the budget.", dueDate: "05-12-2025", status: "todo" },
        ]
    },
    // Project 9: Data Analytics Platform
    {
        title: "Data Analytics Platform Build-out",
        description: "Create a centralized data analytics and business intelligence platform.",
        status: "active",
        tasks: [
            { title: "Identify key business metrics and KPIs", description: "Work with departments to define what needs to be measured.", dueDate: "03-10-2025", status: "done" },
            { title: "Identify and inventory data sources", description: "Map out all databases and APIs (Sales, Marketing, Product).", dueDate: "07-10-2025", status: "done" },
            { title: "Choose a data warehousing solution (e.g., BigQuery)", description: "Select the central repository for our data.", dueDate: "11-10-2025", status: "done" },
            { title: "Select a BI and visualization tool (e.g., Tableau)", description: "Choose the software for creating dashboards.", dueDate: "15-10-2025", status: "in-progress" },
            { title: "Develop ETL pipelines for key data sources", description: "Build the processes to Extract, Transform, and Load data.", dueDate: "20-10-2025", status: "in-progress" },
            { title: "Design the data warehouse schema", description: "Structure the tables for optimal query performance.", dueDate: "24-10-2025", status: "in-progress" },
            { title: "Build the first executive-level dashboard", description: "Create a high-level overview of company performance.", dueDate: "29-10-2025", status: "todo" },
            { title: "Create a marketing performance dashboard", description: "Visualize campaign ROI, CAC, and lead conversion.", dueDate: "03-11-2025", status: "todo" },
            { title: "Build a sales pipeline dashboard", description: "Track deals, conversion rates, and sales rep performance.", dueDate: "07-11-2025", status: "todo" },
            { title: "Develop a product usage and engagement dashboard", description: "Analyze user behavior within the app.", dueDate: "12-11-2025", status: "todo" },
            { title: "Set up data governance and quality checks", description: "Implement processes to ensure data accuracy.", dueDate: "17-11-2025", status: "todo" },
            { title: "Train key users on the BI tool", description: "Teach analysts and managers how to create their own reports.", dueDate: "21-11-2025", status: "todo" },
            { title: "Document all data models and dashboards", description: "Create a data dictionary and user guides.", dueDate: "26-11-2025", status: "todo" },
            { title: "Launch the platform to the wider company", description: "Announce the availability of the new dashboards.", dueDate: "01-12-2025", status: "todo" },
            { title: "Gather feedback and plan for version 2", description: "Collect user requests for new dashboards and data sources.", dueDate: "10-12-2025", status: "todo" },
        ]
    },
    // Project 10: ISO 27001 Certification
    {
        title: "ISO 27001 Security Certification",
        description: "Achieve ISO 27001 certification for our information security management system.",
        status: "active",
        tasks: [
            { title: "Conduct initial gap analysis", description: "Compare our current security practices against ISO 27001 standards.", dueDate: "02-10-2025", status: "done" },
            { title: "Define the scope of the ISMS", description: "Determine which parts of the organization will be certified.", dueDate: "06-10-2025", status: "done" },
            { title: "Develop the information security policy", description: "Create the high-level policy document.", dueDate: "10-10-2025", status: "in-progress" },
            { title: "Conduct a formal risk assessment", description: "Identify and evaluate information security risks.", dueDate: "16-10-2025", status: "in-progress" },
            { title: "Develop a risk treatment plan", description: "Define controls and actions to mitigate identified risks.", dueDate: "21-10-2025", status: "in-progress" },
            { title: "Implement required security controls", description: "Deploy technical and procedural safeguards (e.g., access control).", dueDate: "28-10-2025", status: "todo" },
            { title: "Create documentation for all policies and procedures", description: "Write down all processes as required by the standard.", dueDate: "04-11-2025", status: "todo" },
            { title: "Conduct security awareness training for all staff", description: "Educate employees on their security responsibilities.", dueDate: "10-11-2025", status: "todo" },
            { title: "Perform an internal audit", description: "Have an internal team review the ISMS for compliance.", dueDate: "17-11-2025", status: "todo" },
            { title: "Conduct a management review meeting", description: "Present the internal audit results to leadership.", dueDate: "21-11-2025", status: "todo" },
            { title: "Address any non-conformities from the internal audit", description: "Fix any issues found during the internal review.", dueDate: "28-11-2025", status: "todo" },
            { title: "Select and hire an external certification body", description: "Choose the accredited company to perform the official audit.", dueDate: "03-12-2025", status: "todo" },
            { title: "Undergo Stage 1 external audit", description: "The external auditor reviews our documentation.", dueDate: "10-12-2025", status: "todo" },
            { title: "Undergo Stage 2 external audit", description: "The external auditor performs an on-site inspection.", dueDate: "20-12-2025", status: "todo" },
            { title: "Receive ISO 27001 certification", description: "Successfully complete the audit and get certified.", dueDate: "15-01-2026", status: "todo" },
        ]
    },
    // Project 11: Customer Support System Upgrade
    {
        title: "Customer Support System Upgrade",
        description: "Replace the legacy support ticketing system with a modern platform like Zendesk.",
        status: "active",
        tasks: [
            { title: "Analyze current support workflow and pain points", description: "Interview support agents and managers.", dueDate: "29-09-2025", status: "done" },
            { title: "Define requirements for the new system", description: "List all must-have features (e.g., multi-channel support, SLAs).", dueDate: "02-10-2025", status: "done" },
            { title: "Evaluate and select a new support platform vendor", description: "Compare Zendesk, Freshdesk, Intercom, etc.", dueDate: "07-10-2025", status: "done" },
            { title: "Plan migration of existing ticket data", description: "Decide which historical data needs to be moved.", dueDate: "11-10-2025", status: "in-progress" },
            { title: "Configure the new platform's settings", description: "Set up business hours, ticket fields, and automations.", dueDate: "15-10-2025", status: "in-progress" },
            { title: "Integrate with email and social media channels", description: "Connect all support channels to the new platform.", dueDate: "18-10-2025", status: "in-progress" },
            { title: "Build out the new knowledge base/FAQ section", description: "Migrate or create new self-help articles for customers.", dueDate: "22-10-2025", status: "todo" },
            { title: "Set up SLA policies and automated reminders", description: "Define response and resolution time targets.", dueDate: "25-10-2025", status: "todo" },
            { title: "Import customer and historical ticket data", description: "Execute the planned data migration.", dueDate: "29-10-2025", status: "todo" },
            { title: "Train all customer support agents", description: "Conduct training sessions on the new platform.", dueDate: "03-11-2025", status: "todo" },
            { title: "Conduct user acceptance testing with the support team", description: "Have agents test the full workflow.", dueDate: "06-11-2025", status: "todo" },
            { title: "Update website 'Contact Us' page and links", description: "Point all support forms and links to the new system.", dueDate: "10-11-2025", status: "todo" },
            { title: "Go-live with the new support system", description: "Switch over from the old system to the new one.", dueDate: "12-11-2025", status: "todo" },
            { title: "Monitor system performance and agent adoption", description: "Track key metrics during the first week.", dueDate: "19-11-2025", status: "todo" },
            { title: "Decommission the old ticketing system", description: "Archive data and terminate the old subscription.", dueDate: "26-11-2025", status: "todo" },
        ]
    },
    // Project 12: Content Strategy for 2026
    {
        title: "Content Strategy for 2026",
        description: "Develop a comprehensive content marketing strategy for the upcoming year.",
        status: "active",
        tasks: [
            { title: "Review 2025 content performance", description: "Analyze what worked and what didn't across the blog and social.", dueDate: "01-10-2025", status: "done" },
            { title: "Conduct keyword research and topic ideation", description: "Identify target SEO keywords and content pillars.", dueDate: "06-10-2025", status: "done" },
            { title: "Analyze competitor content strategies", description: "See what topics and formats competitors are using successfully.", dueDate: "10-10-2025", status: "in-progress" },
            { title: "Define target audience and content personas", description: "Refine our understanding of who we are creating content for.", dueDate: "14-10-2025", status: "in-progress" },
            { title: "Define content goals and metrics for 2026", description: "Set targets for traffic, leads, and engagement.", dueDate: "17-10-2025", status: "in-progress" },
            { title: "Plan major content campaigns for each quarter", description: "Outline the big-rock content pieces for the year.", dueDate: "22-10-2025", status: "todo" },
            { title: "Create a detailed editorial calendar for Q1 2026", description: "Schedule blog posts, videos, and social media content.", dueDate: "28-10-2025", status: "todo" },
            { title: "Establish content creation workflows and guidelines", description: "Define the process from ideation to publication.", dueDate: "03-11-2025", status: "todo" },
            { title: "Allocate content budget for freelancers and tools", description: "Plan spending for writing, design, and software.", dueDate: "07-11-2025", status: "todo" },
            { title: "Plan video content strategy for YouTube", description: "Decide on series, formats, and frequency for video.", dueDate: "12-11-2025", status: "todo" },
            { title: "Develop a plan for content distribution and promotion", description: "Strategize how to get eyeballs on our content.", dueDate: "17-11-2025", status: "todo" },
            { title: "Plan for repurposing content across formats", description: "Create a system to turn blog posts into videos, etc.", dueDate: "21-11-2025", status: "todo" },
            { title: "Finalize and present the 2026 content strategy", description: "Get buy-in from leadership and stakeholders.", dueDate: "28-11-2025", status: "todo" },
            { title: "Begin creating content for January 2026", description: "Get a head start on the new year's content.", dueDate: "05-12-2025", status: "todo" },
            { title: "Set up tracking and reporting dashboards", description: "Create analytics dashboards to monitor performance.", dueDate: "12-12-2025", status: "todo" },
        ]
    }
  ],
};

module.exports = seedData;